### PR TITLE
Documented how to run telseq on Docker

### PR DESCRIPTION
**Pull request by dlcotter**

### CODE REVIEW

**Comment by pbilling** [comment]
Hi Daniel, looks good! A few thoughts:

* Add a docker/README.md that provides some more context, e.g. “This is a tutorial where you will learn to run containerized bioinformatics software on a cloud virtual machine. We will be using the telomere software “telseq”, as our example use case.”
* Provide some more information on creating a virtual machine using a container (step 7)
* We don’t want to share cloud project IDs, so please replace instances of them with bash variables or similar
* authenticate-docker doc reads like an error message rather than a tutorial. Maybe you could swap the phrasing; “I need to authorize docker to write to my container repository… or I will get an error.”
* They should probably run telseq in the container before pushing it, to validate that it works, i.e. move step 8 to step 4. Also, please specify where/how to get the sample.bam
* It would be nice to have a final step where they bring it all together by running telseq on a sample.bam on the VM

**Comment by dlcotter** [comment]
I fixed the issues you brought up, except for where to find the sample BAM (I couldn't remember where I got it, tbh)

**Review by pbilling — COMMENTED** [review]
Looks good!

**Comment by vembuprathima** [comment]
Hi @dlcotter , I think you could try running telseq with the [test bams](https://github.com/zd1/telseq/tree/master/src/Test) that the authors have provided, given you are getting 0's for your output. I have the results for the same:
- Command ``` docker run -v /path/to/test.1.bam:/sample.bam telseq-docker -k 7 -r 100 /sample.bam```
- To build the image I followed the same steps as [this](https://github.com/zd1/telseq#build-telseq-docker-image)

- test.1.bam 
Screenshot 2023-02-03 at 10 40 02 AM

- test.2.bam 
Screenshot 2023-02-03 at 10 40 24 AM

- test.3.bam  
Screenshot 2023-02-03 at 10 40 37 AM

**Pull request merged**
